# Generated by Django 3.0.3 on 2020-02-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text='类别名', max_length=30, verbose_name='类别名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=25, verbose_name='标签名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('brief', models.CharField(blank=True, default='这篇文章没有摘要', max_length=255, verbose_name='文章摘要')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/articles/covers/')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogCategory', verbose_name='文章类别')),
                ('tags', models.ManyToManyField(blank=True, to='blog.BlogTag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-modify_time'],
            },
        ),
    ]
