# Generated by Django 3.0.3 on 2020-02-12 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类别名', max_length=30, verbose_name='类别名')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='标签名')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('brief', models.CharField(blank=True, default='这篇文章没有摘要', max_length=255, verbose_name='文章摘要')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='blogs/articles/covers/')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论量')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.BlogCategory', verbose_name='文章类别')),
                ('tags', models.ManyToManyField(blank=True, to='blogs.BlogTag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
