# Generated by Django 3.0.3 on 2020-02-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
