# Generated by Django 3.0.3 on 2020-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200216_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'ordering': ['-add_time'], 'verbose_name': '验证码', 'verbose_name_plural': '验证码'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='邮箱'),
        ),
    ]
